# Site
repository: Refal/egor_cv
# favicon: images/favicon.ico

# Personal info
name: Egor Surovtsev
title: Software Engineer at Zalando SE
location: Berlin, Germany
phone: +49 163 043 76 47
email: esurovtsev@gmail.com
website: www.github.com/refal

# Social links
twitter_username: Refal82
github_username:  refal
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: esurovtsev
linkedin_username: esurovtsev
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/egor_1.jpg
about_content: | # this will include new lines to allow paragraphs

  * A full-stack Java developer with more than 10 years of experience in software engineering
  * 2 years scala
  * 8 years of experience in Enterprise applications development (Trading/Banking) and more than 2 years in E-commerce
  * The combination of technical (Senior Developer) and management (Team Lead/SCRUM Master) background is helping a lot to balance between being keen on code quality and pragmatic focusing on the actual result
  * Keen on Agile processes as a tool helping teams to be effective in getting things done
  * Keen on continuous delivery as a way of making those things live smoothly and seamlessly
  * Keen on automating every routine piece of work not meant for humans

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# educaton_title: Education

# More Section
# more_title: My hobbies
more_content: | # this will include new lines to allow paragraphs
  * I am keen on traveling and visited already more than 30 countries
  * Hiking - I am trying to go out for at weekend and walk around 20 km per day

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
